base_model = "mistral/mistral-small-2506"

name = "Mistral Small 3.2 24b Instruct"
tool_call = false
structured_output = false

[cost]
input = 0.2
output = 0.4
cache_read = 0.1

[limit]
input = 128_000
output = 131_072

[modalities]
input = ["text"]
output = ["text"]
