base_model = "mistral/open-mistral-7b"
name = "Mistral 7B Instruct v0.3"
description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
release_date = "2024-05-22"

[limit]
output = 32_768
