base_model = "mistral/ministral-3b-2512"

name = "ministral-3b-2512"
description = "Ministral 3 3B is a compact, efficient multimodal model with strong language, vision capabilities, and ideal for custom fine-tuning."
temperature = false

[cost]
input = 0.111
output = 0.111
cache_read = 0.011
