base_model = "mistral/mistral-small-2506"

name = "mistral-small-3.2-24b-instruct-2506"
description = "Mistral-Small-3.2-24B-Instruct-2506 is a 24B parameter instruction-tuned model with enhanced long-context support (128k) and state-of-the-art vision understanding."
attachment = true
temperature = false
structured_output = true

[cost]
input = 0.1
output = 0.312

[limit]
context = 131_000
output = 131_000
