base_model = "mistral/mistral-small-3-1-24b-instruct-2503"

name = "mistral-small-2503"
description = "Combines advanced text and vision capabilities with 24 billion parameters, supporting multilingual tasks and long contexts up to 131k tokens, making it versatile for various applications without sacrificing performance."
temperature = false

[cost]
input = 0.111
output = 0.334

[limit]
output = 128_000
