base_model = "mistral/mistral-medium-2508"

name = "mistral-medium-2508"
description = "Mistral Medium 2508 is a frontier-class multimodal LLM with a 128,000 token context window, optimized for reasoning, coding, and multimodal tasks."
reasoning = true
temperature = false
reasoning_options = []

[cost]
input = 0.446
output = 2.228
cache_read = 0.045

[limit]
context = 128_000
output = 128_000
