base_model = "mistral/open-mistral-7b"

name = "mistral-7b-instruct-v0.2"
description = "Mistral 7B Instruct is a compact, 7B parameter model optimized for fast and efficient text and code generation with a 32K token context window."
attachment = true
temperature = false
tool_call = false
structured_output = false

[cost]
input = 0.159
output = 0.219

[limit]
context = 32_000
output = 32_000

[modalities]
input = ["text", "pdf"]
output = ["text"]
