base_model = "mistral/mistral-small-3-1-24b-instruct-2503"

name = "Mistral Small 31 24b Instruct"
description = "Compact GPT model for low-latency assistance and high-volume workloads"
tool_call = false
structured_output = false

[cost]
input = 0.1
output = 0.3
cache_read = 0.05

[limit]
input = 128_000
output = 131_072
