base_model = "mistral/open-mixtral-8x22b"
name = "Mistral: Mixtral 8x22B Instruct"
description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"

[cost]
input = 0.0
output = 0.0

[limit]
context = 65_536
output = 13_108
