base_model = "mistral/mistral-saba-2502"

description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
tool_call = false
structured_output = false

[cost]
input = 0.1989
output = 0.595
cache_read = 0.09945

[limit]
input = 32_000
output = 32_768
