base_model = "mistral/mistral-medium-2508"

description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
attachment = false
tool_call = false
structured_output = false

[cost]
input = 0.4
output = 2
cache_read = 0.2

[limit]
input = 131_072
output = 32_768

[modalities]
input = ["text"]
output = ["text"]
