base_model = "mistral/mistral-nemo"

description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
tool_call = false
structured_output = false

[cost]
input = 0.1003
output = 0.1207
cache_read = 0.05015

[limit]
context = 16_384
input = 16_384
output = 8_192
