base_model = "mistral/mistral-small-2506"
name = "Mistral Small 3.2 24B Instruct"
release_date = "2026-01-15"
last_updated = "2026-06-11"
structured_output = true

[cost]
input = 0.09375
output = 0.25

[limit]
context = 256_000

[modalities]
input = ["text"]
