base_model = "mistral/mistral-small-2501"

name = "Mistral Small 3"
description = "Efficient Mistral model for fast chat, extraction, and production assistants"
tool_call = false
knowledge = "2023-10-31"

[cost]
input = 0.05
output = 0.08

[limit]
output = 16_384
