base_model = "mistral/mistral-medium-2508"

description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
release_date = "2025-08-13"
last_updated = "2025-08-13"
knowledge = "2025-06-30"

[cost]
input = 0.4
output = 2
cache_read = 0.04

[limit]
output = 104_857

[modalities]
input = ["text", "image", "pdf"]
