base_model = "mistral/mistral-small-3-1-24b-instruct-2503"

description = "Efficient Mistral model for fast chat, extraction, and production assistants"
tool_call = false
structured_output = false
knowledge = "2023-10-31"

[cost]
input = 0.351
output = 0.555

[limit]
output = 102_400
