base_model = "mistral/mistral-small-2506"

name = "Mistral Small 3.2 24B"
attachment = true
structured_output = true
knowledge = "2023-10-31"

[cost]
input = 0.075
output = 0.2

[limit]
context = 131_072
