name = "Mistral 7B Instruct v0.2"
description = "Mistral 7B Instruct is a compact, 7B parameter model optimized for fast and efficient text and code generation with a 32K token context window."
family = "mistral"
release_date = "2025-05-26"
last_updated = "2025-05-26"
attachment = true
reasoning = false
temperature = false
tool_call = false
structured_output = false
open_weights = false

[limit]
context = 32_000
output = 32_000

[modalities]
input = ["text", "pdf"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2"
