base_model = "mistral/mistral-small-2501"
name = "Mistral: Mistral Small 3"
description = "Efficient Mistral model for fast chat, extraction, and production assistants"
tool_call = false
open_weights = false

[cost]
input = 0.05
output = 0.08

[limit]
context = 32_768
output = 16_384
