base_model = "mistral/mistral-large-2512"
name = "Mistral Large"
release_date = "2024-02-26"
last_updated = "2024-02-26"
structured_output = true
open_weights = false

[cost]
input = 2
output = 6
cache_read = 0.2

[limit]
context = 128_000
output = 102_400

[modalities]
input = ["text", "pdf"]
output = ["text"]
