base_model = "mistral/mistral-small-3-1-24b-instruct-2503"
name = "Mistral: Mistral Small 3.1 24B"
description = "Efficient Mistral model for fast chat, extraction, and production assistants"
tool_call = false
structured_output = false
open_weights = false

[cost]
input = 0.351
output = 0.555

[limit]
context = 128_000
output = 102_400
