base_model = "mistral/mistral-large-2411"
name = "Mistral-Large"
release_date = "2024-07-24"
last_updated = "2024-07-24"
knowledge = "2024-07"
open_weights = false

[cost]
input = 2
output = 6

[limit]
context = 128000
output = 32768
