base_model = "mistral/mistral-small-2506"
name = "Mistral Small 3.2 24B Instruct"
attachment = true
knowledge = "2024-10"
structured_output = true

[cost]
input = 0
output = 0

[limit]
context = 32_768
output = 8_192
