base_model = "mistral/mistral-nemo"
name = "Mistral Nemo 12B Instruct"
description = "Mistral model for multilingual chat, reasoning, and tool-assisted workflows"
release_date = "2025-01-01"
last_updated = "2025-01-01"
knowledge = "2024-12"

[cost]
input = 0.038
output = 0.10

[limit]
context = 16_000
output = 4_096
